#!/usr/bin/env bash
# loops from 1 to 10 and:
#   displays bad luck for the 4th loop iteration
#   displays good luck for the 8th loop iteration
#   displays Best School for the other iterations

count=0

while [ $count -lt 10 ]; do
	((count++))
	if [ $count -eq 4 ]; then
		echo "bad luck"
		continue
	elif [ $count -eq 8 ]; then
		echo "good luck"
		continue
	else
		echo "Best School"
	fi
done
