#!/usr/bin/env bash
# Bash script that gives you information about the school file
file_to_check="school"

if [ -e $file_to_check ]; then
	echo "school file exists"
	if [ -s $file_to_check ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $file_to_check ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
